import os
from flask import Flask, render_template, request, jsonify
from spotify_client import get_client

app = Flask(__name__)


def find_artist(sp, name):
    results = sp.search(q=name, type="artist", limit=1)
    items = results["artists"]["items"]
    if not items:
        return None, None
    return items[0]["id"], items[0]["name"]


def get_top_tracks(sp, artist_id, artist_name, max_tracks):
    results = sp.search(q=f'artist:"{artist_name}"', type="track", limit=50, market="US")
    tracks = [
        t for t in results["tracks"]["items"]
        if any(a["id"] == artist_id for a in t["artists"])
    ]
    tracks.sort(key=lambda t: t.get("popularity") or 0, reverse=True)
    return [t["uri"] for t in tracks[:max_tracks]]


@app.route("/")
def index():
    preset = ""
    try:
        with open("artists.txt") as f:
            preset = f.read()
    except FileNotFoundError:
        pass
    return render_template("index.html", artists_preset=preset)


@app.route("/api/create-playlist", methods=["POST"])
def create_playlist():
    data = request.json or {}
    artists_input = data.get("artists", [])
    playlist_name = data.get("playlist_name", "").strip()

    if not artists_input:
        return jsonify({"error": "No artists provided"}), 400
    if len(artists_input) > 50:
        return jsonify({"error": "Maximum 50 artists allowed"}), 400

    sp = get_client()

    all_uris = []
    found_names = []
    artist_results = []

    for entry in artists_input:
        name = (entry.get("name") or "").strip()
        if not name:
            continue
        max_tracks = max(1, min(int(entry.get("tracks", 3)), 20))

        artist_id, canonical = find_artist(sp, name)
        if not artist_id:
            artist_results.append({"name": name, "found": False, "tracks": 0})
            continue

        uris = get_top_tracks(sp, artist_id, canonical, max_tracks)
        all_uris.extend(uris)
        found_names.append(canonical)
        artist_results.append({"name": name, "canonical": canonical, "found": True, "tracks": len(uris)})

    if not all_uris:
        return jsonify({"error": "No tracks found for any of the provided artists"}), 400

    if not playlist_name:
        label = ", ".join(found_names[:5])
        if len(found_names) > 5:
            label += f" +{len(found_names) - 5} more"
        playlist_name = f"Top Tracks: {label}"
    if len(playlist_name) > 100:
        playlist_name = playlist_name[:97] + "..."

    user = sp.me()
    playlist = sp.user_playlist_create(
        user["id"],
        playlist_name,
        public=True,
        description="Generated by SpotifyPy",
    )
    playlist_id = playlist["id"]

    for i in range(0, len(all_uris), 100):
        sp.playlist_add_items(playlist_id, all_uris[i:i + 100])

    return jsonify({
        "success": True,
        "playlist_id": playlist_id,
        "url": f"https://open.spotify.com/playlist/{playlist_id}",
        "playlist_name": playlist_name,
        "total_tracks": len(all_uris),
        "artists_found": len(found_names),
        "artists": artist_results,
    })


if __name__ == "__main__":
    app.run(debug=True, port=5000)
