import sys
from spotify_client import get_client

ARTISTS_FILE = "artists.txt"
MAX_TRACKS_PER_ARTIST = 3


def read_artists(filepath: str) -> list[str]:
    with open(filepath) as f:
        return [line.strip() for line in f if line.strip()]


def find_artist(sp, artist_name: str) -> tuple[str, str] | tuple[None, None]:
    results = sp.search(q=artist_name, type="artist", limit=1)
    items = results["artists"]["items"]
    if not items:
        print(f"Warning: artist not found — '{artist_name}'")
        return None, None
    return items[0]["id"], items[0]["name"]


def get_top_tracks(sp, artist_id: str, artist_name: str, max_tracks: int = MAX_TRACKS_PER_ARTIST) -> list[str]:
    results = sp.search(q=f'artist:"{artist_name}"', type="track", limit=10, market="US")
    tracks = [
        t for t in results["tracks"]["items"]
        if any(a["id"] == artist_id for a in t["artists"])
    ]
    tracks.sort(key=lambda t: t.get("popularity") or 0, reverse=True)
    return [t["uri"] for t in tracks[:max_tracks]]


def create_playlist(sp, name: str, description: str) -> str:
    payload = {"name": name, "public": True, "description": description}
    playlist = sp._post("me/playlists", payload=payload)
    return playlist["id"]


def add_tracks(sp, playlist_id: str, track_uris: list[str]) -> None:
    for i in range(0, len(track_uris), 100):
        sp.playlist_add_items(playlist_id, track_uris[i:i + 100])


def main():
    sp = get_client()

    artists = read_artists(ARTISTS_FILE)
    if not artists:
        print("No artists found in artists.txt")
        sys.exit(1)

    print(f"Processing {len(artists)} artist(s)...")

    all_uris: list[str] = []
    found_artists: list[str] = []

    for name in artists:
        artist_id, canonical_name = find_artist(sp, name)
        if not artist_id:
            continue
        uris = get_top_tracks(sp, artist_id, canonical_name)
        if uris:
            all_uris.extend(uris)
            found_artists.append(name)
            print(f"  {name}: {len(uris)} track(s) added")

    if not all_uris:
        print("No tracks found. Exiting.")
        sys.exit(1)

    label = ", ".join(found_artists)
    playlist_name = f"Top Tracks: {label}"
    if len(playlist_name) > 100:
        playlist_name = f"Top Tracks: {label[:96]}..."

    playlist_id = create_playlist(
        sp,
        name=playlist_name,
        description=f"Top {MAX_TRACKS_PER_ARTIST} tracks per artist. Generated by SpotifyPy.",
    )

    add_tracks(sp, playlist_id, all_uris)

    print(f"\nPlaylist created with {len(all_uris)} tracks:")
    print(f"https://open.spotify.com/playlist/{playlist_id}")


if __name__ == "__main__":
    main()
